import type { NextApiRequest, NextApiResponse } from 'next'

const TOPIC_SLUGS = [
  'acute-coronary-syndrome', 'arrhythmias', 'atrial-fibrillation',
  'aortic-disease', 'cardiomyopathy', 'heart-failure', 'hyperlipidaemia',
  'hypertension', 'infective-endocarditis', 'pericardial-disease',
  'stable-coronary-artery-disease', 'valvular-heart-disease',
  'asthma', 'community-acquired-pneumonia', 'copd', 'pleural-effusion',
  'pneumothorax', 'pulmonary-embolism', 'pulmonary-hypertension',
  'respiratory-failure', 'sepsis-and-shock', 'tuberculosis',
  'cirrhosis-and-liver-disease', 'colorectal-disease', 'ibs-and-functional-gi',
  'inflammatory-bowel-disease', 'pancreatitis', 'upper-gi-disease',
  'acid-base-disorders', 'acute-kidney-injury', 'chronic-kidney-disease',
  'fluid-and-electrolyte-disorders', 'glomerular-disease', 'nephrolithiasis',
  'urinary-tract-infections', 'cns-infections', 'dementia',
  'epilepsy-and-seizures', 'headache', 'movement-disorders',
  'multiple-sclerosis', 'neuromuscular-disease', 'stroke-and-tia',
  'adrenal-disease', 'diabetes-mellitus', 'pituitary-and-calcium',
  'reproductive-endocrinology', 'thyroid-disease', 'anaemia',
  'bleeding-disorders-and-thrombosis', 'haematological-malignancies',
  'haemolytic-anaemia-and-bone-marrow-failure', 'oncology-principles',
  'connective-tissue-diseases', 'crystal-arthropathies-and-vasculitis',
  'msk-and-osteoporosis', 'rheumatoid-arthritis',
  'seronegative-spondyloarthropathies', 'antimicrobial-stewardship',
  'fever-and-immu
